* Encoding: UTF-8.

*Normalizar variables.
DESCRIPTIVES VARIABLES=P05 P24 P35AO P386
  /SAVE
  /STATISTICS=MEAN STDDEV MIN MAX.

* Clasificar por k medias.
QUICK CLUSTER ZP05 ZP24 ZP35AO ZP386
  /MISSING=LISTWISE
  /CRITERIA=CLUSTER(3) MXITER(10) CONVERGE(0)
  /METHOD=KMEANS(NOUPDATE)
  /SAVE CLUSTER
  /PRINT INITIAL.

GRAPH
  /SCATTERPLOT(MATRIX)=ZP05 ZP24 ZP35AO ZP386 BY QCL_1
  /MISSING=LISTWISE.

* Clasificar por jerárquico con gráfico de dendrogama.
CLUSTER   ZP05 ZP24 ZP35AO ZP386
  /METHOD BAVERAGE
  /MEASURE=SEUCLID
  /PRINT SCHEDULE
  /PLOT DENDROGRAM VICICLE
  /SAVE CLUSTER(3).

* Clasificación bietápica.
TWOSTEP CLUSTER
  /CATEGORICAL VARIABLES=P02 P06 P07 P10 P11 P08 COD
  /CONTINUOUS VARIABLES=P05 P35AO P387
  /DISTANCE LIKELIHOOD
  /NUMCLUSTERS AUTO 15 BIC
  /HANDLENOISE 0
  /MEMALLOCATE 64
  /CRITERIA INITHRESHOLD(0) MXBRANCH(8) MXLEVEL(3)
  /VIEWMODEL DISPLAY=YES.
